/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.csc0103_intermediate_programming;

import java.awt.Color;
import java.util.Random;
import javax.swing.JToggleButton;

/**
 *
 * @author vhenz
 */
public class MainConsole_Draft extends javax.swing.JFrame {

    public int N;
    /**
     * Creates new form MainConsole_Draft
     */
    public MainConsole_Draft() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        Main = new javax.swing.JPanel();
        P1_Btn = new javax.swing.JButton();
        P2_Btn = new javax.swing.JButton();
        P3_Btn = new javax.swing.JButton();
        P4_Btn = new javax.swing.JButton();
        P5_Btn = new javax.swing.JButton();
        P6_Btn = new javax.swing.JButton();
        P7_Btn = new javax.swing.JButton();
        P8_Btn = new javax.swing.JButton();
        P9_Btn = new javax.swing.JButton();
        P10_Btn = new javax.swing.JButton();
        AbtGroup_Btn = new javax.swing.JButton();
        MainTitle = new javax.swing.JLabel();
        main_spacefill_left = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        main_spacefill_right = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        MainTitle2 = new javax.swing.JLabel();
        Main_Label = new javax.swing.JLabel();
        PR1_Panel = new javax.swing.JPanel();
        PR1_InputArea_Main = new javax.swing.JTextField();
        PR1_Output_Scroll = new javax.swing.JScrollPane();
        PR1_OutputArea = new javax.swing.JTextArea();
        PR1_Next_Btn = new javax.swing.JButton();
        PR1_Return_Btn = new javax.swing.JButton();
        PR1_Output_Label = new javax.swing.JLabel();
        filler35 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        PR1_Clear_Btn = new javax.swing.JButton();
        PR1_CelToFar = new javax.swing.JButton();
        PR1_LeastCmonMult = new javax.swing.JButton();
        PR1_CubeRt = new javax.swing.JButton();
        PR1_Rand = new javax.swing.JButton();
        PR1_FarToCel = new javax.swing.JButton();
        PR1_BinToOct = new javax.swing.JButton();
        PR1_SqrRt = new javax.swing.JButton();
        PR1_Factorials = new javax.swing.JButton();
        PR1_InputArea_Sub = new javax.swing.JTextField();
        PR1_Input_Label1 = new javax.swing.JLabel();
        PR1_Input_Label2 = new javax.swing.JLabel();
        PR1_Input_Label3 = new javax.swing.JLabel();
        PR1_Vert_Filler = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        PR2_Panel = new javax.swing.JPanel();
        PR2_Clear_Btn = new javax.swing.JButton();
        PR2_Compute_Btn = new javax.swing.JButton();
        PR2_Buffer_1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        PR2_Output_Scroll = new javax.swing.JScrollPane();
        PR2_OutputArea = new javax.swing.JTextArea();
        PR2_Next_Btn = new javax.swing.JButton();
        PR2_Back_Btn = new javax.swing.JButton();
        PR2_Label_Input = new javax.swing.JLabel();
        PR2_Return_Btn = new javax.swing.JButton();
        PR2_InitVal_Input = new javax.swing.JTextField();
        PR2_IntRate_Input = new javax.swing.JTextField();
        PR2_TimeYr_Input = new javax.swing.JTextField();
        Label_PrincipalAmount = new javax.swing.JLabel();
        PR2_Label_Years = new javax.swing.JLabel();
        PR2_Rate = new javax.swing.JLabel();
        PR2_Label_Output = new javax.swing.JLabel();
        PR2_Label_Input1 = new javax.swing.JLabel();
        PR2_Vert_Filler = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        PR3_Panel = new javax.swing.JPanel();
        PR3_Clear_Btn = new javax.swing.JButton();
        PR3_rightFill = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        PR3_About = new javax.swing.JButton();
        PR3_Back = new javax.swing.JButton();
        PR3_Compute_Btn = new javax.swing.JButton();
        PR3_Return = new javax.swing.JButton();
        PR3_PrincipalAmount_Label = new javax.swing.JLabel();
        PR3_FutVal_Output = new javax.swing.JTextField();
        PR3_IntEarn_Label = new javax.swing.JLabel();
        PR3_Input_InterestRate = new javax.swing.JTextField();
        PR3_Input_TimeYear = new javax.swing.JTextField();
        PR3_Years_Input = new javax.swing.JLabel();
        PR3_Input_Label = new javax.swing.JLabel();
        PR3_Input_InitialValue = new javax.swing.JTextField();
        PR3_Annual_Toggle = new javax.swing.JToggleButton();
        Semi_Annuall_Toggle = new javax.swing.JToggleButton();
        Monthly_Toggle = new javax.swing.JToggleButton();
        Weekly_Toggle = new javax.swing.JToggleButton();
        Quarterly_Toggle = new javax.swing.JToggleButton();
        Daily_Toggle = new javax.swing.JToggleButton();
        PR3_IntEarn_Output = new javax.swing.JTextField();
        PR3_Output_Label = new javax.swing.JLabel();
        PR3_IntRate_Label = new javax.swing.JLabel();
        PR3_FutVal_Label = new javax.swing.JLabel();
        Label_PrincipalAmount2 = new javax.swing.JLabel();
        Label_PrincipalAmount3 = new javax.swing.JLabel();
        PR3_Label = new javax.swing.JLabel();
        PR3_Vert_Filler = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        AbtGrp_Panel = new javax.swing.JPanel();
        AbtGrp_Return = new javax.swing.JButton();
        NameGrp = new javax.swing.JPanel();
        Members = new javax.swing.JLabel();
        Bonifacio = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PR3_Vert_Filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        AbtGrp_rightFill = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        AbtGrp_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));

        Content.setBackground(new java.awt.Color(255, 255, 204));
        Content.setLayout(new java.awt.CardLayout());

        Main.setBackground(new java.awt.Color(255, 255, 204));
        Main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Main.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                MainComponentHidden(evt);
            }
        });
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P1_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P1_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P1_Btn.setText("Binary To Octal");
        P1_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P1_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1_BtnActionPerformed(evt);
            }
        });
        Main.add(P1_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 187, 60));

        P2_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P2_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P2_Btn.setText("Random Number Generator");
        P2_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P2_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2_BtnActionPerformed(evt);
            }
        });
        Main.add(P2_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 187, 60));

        P3_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P3_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P3_Btn.setText("Simple Interest");
        P3_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P3_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P3_BtnActionPerformed(evt);
            }
        });
        Main.add(P3_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 187, 60));

        P4_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P4_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P4_Btn.setText("Compound Interest");
        P4_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P4_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P4_BtnActionPerformed(evt);
            }
        });
        Main.add(P4_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 187, 60));

        P5_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P5_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P5_Btn.setText("Celsius to Farenheit");
        P5_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P5_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P5_BtnActionPerformed(evt);
            }
        });
        Main.add(P5_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 187, 60));

        P6_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P6_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P6_Btn.setText("Farenheit to Celsius");
        P6_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P6_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P6_BtnActionPerformed(evt);
            }
        });
        Main.add(P6_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 187, 60));

        P7_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P7_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P7_Btn.setText("Cuberoot Checker");
        P7_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P7_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P7_BtnActionPerformed(evt);
            }
        });
        Main.add(P7_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 187, 60));

        P8_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P8_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P8_Btn.setText("Square Root Checker");
        P8_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P8_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P8_BtnActionPerformed(evt);
            }
        });
        Main.add(P8_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 187, 60));

        P9_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P9_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P9_Btn.setText("Factorials");
        P9_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P9_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P9_BtnActionPerformed(evt);
            }
        });
        Main.add(P9_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 187, 60));

        P10_Btn.setBackground(new java.awt.Color(153, 153, 255));
        P10_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        P10_Btn.setText("Least Common Multiple");
        P10_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        P10_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P10_BtnActionPerformed(evt);
            }
        });
        Main.add(P10_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 187, 60));

        AbtGroup_Btn.setBackground(new java.awt.Color(153, 153, 255));
        AbtGroup_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        AbtGroup_Btn.setText("About");
        AbtGroup_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        AbtGroup_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbtGroup_BtnActionPerformed(evt);
            }
        });
        Main.add(AbtGroup_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 410, 60));

        MainTitle.setFont(new java.awt.Font("Garamond", 0, 10)); // NOI18N
        MainTitle.setText("Prof. Jamillah Gualil");
        Main.add(MainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 90, 20));
        Main.add(main_spacefill_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 110, 30));
        Main.add(main_spacefill_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 110, 30));

        MainTitle2.setFont(new java.awt.Font("Garamond", 0, 10)); // NOI18N
        MainTitle2.setText("CSC 0103 Intermediate Programming");
        Main.add(MainTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 160, 20));

        Main_Label.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        Main_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Main_Label.setText("BSCS 1-2 | Group 2| 10 Sample Programs | IP Finals");
        Main.add(Main_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 500, 20));

        Content.add(Main, "card2");

        PR1_Panel.setBackground(new java.awt.Color(255, 255, 204));
        PR1_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR1_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PR1_InputArea_Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_InputArea_MainActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_InputArea_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 380, 70));

        PR1_OutputArea.setBackground(new java.awt.Color(153, 255, 153));
        PR1_OutputArea.setColumns(20);
        PR1_OutputArea.setRows(5);
        PR1_OutputArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR1_OutputArea.setEditable(false);
        PR1_OutputArea.setFocusable(false);
        PR1_OutputArea.setCursor(null);
        PR1_Output_Scroll.setViewportView(PR1_OutputArea);

        PR1_Panel.add(PR1_Output_Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 380, 130));

        PR1_Next_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR1_Next_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_Next_Btn.setText("Next Program");
        PR1_Next_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_Next_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_Next_BtnActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_Next_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 120, 50));

        PR1_Return_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR1_Return_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_Return_Btn.setText("Return to Menu");
        PR1_Return_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_Return_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_Return_BtnActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_Return_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 110, 50));

        PR1_Output_Label.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        PR1_Output_Label.setText("Output");
        PR1_Panel.add(PR1_Output_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));
        PR1_Panel.add(filler35, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 110, 30));

        PR1_Clear_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR1_Clear_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_Clear_Btn.setText("Clear");
        PR1_Clear_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_Clear_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_Clear_BtnActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_Clear_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 200, 40));

        PR1_CelToFar.setBackground(new java.awt.Color(153, 153, 255));
        PR1_CelToFar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_CelToFar.setText("Celsius to Farenheit");
        PR1_CelToFar.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_CelToFar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_CelToFarActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_CelToFar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 170, 30));

        PR1_LeastCmonMult.setBackground(new java.awt.Color(153, 153, 255));
        PR1_LeastCmonMult.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_LeastCmonMult.setText("Least Common Multiple");
        PR1_LeastCmonMult.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_LeastCmonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_LeastCmonMultActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_LeastCmonMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 170, 30));

        PR1_CubeRt.setBackground(new java.awt.Color(153, 153, 255));
        PR1_CubeRt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_CubeRt.setText("Cube Root Checker");
        PR1_CubeRt.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_CubeRt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_CubeRtActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_CubeRt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 170, 30));

        PR1_Rand.setBackground(new java.awt.Color(153, 153, 255));
        PR1_Rand.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_Rand.setText("Random Number Generator");
        PR1_Rand.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_Rand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_RandActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_Rand, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 170, 30));

        PR1_FarToCel.setBackground(new java.awt.Color(153, 153, 255));
        PR1_FarToCel.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_FarToCel.setText("Farenheit to Celsius");
        PR1_FarToCel.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_FarToCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_FarToCelActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_FarToCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 170, 30));

        PR1_BinToOct.setBackground(new java.awt.Color(153, 153, 255));
        PR1_BinToOct.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_BinToOct.setText("Binary To Octal");
        PR1_BinToOct.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_BinToOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_BinToOctActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_BinToOct, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 170, 30));

        PR1_SqrRt.setBackground(new java.awt.Color(153, 153, 255));
        PR1_SqrRt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_SqrRt.setText("Square Root Checker");
        PR1_SqrRt.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_SqrRt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_SqrRtActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_SqrRt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 170, 30));

        PR1_Factorials.setBackground(new java.awt.Color(153, 153, 255));
        PR1_Factorials.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR1_Factorials.setText("Factorials");
        PR1_Factorials.setBorder(new javax.swing.border.MatteBorder(null));
        PR1_Factorials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_FactorialsActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_Factorials, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 170, 30));

        PR1_InputArea_Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR1_InputArea_SubActionPerformed(evt);
            }
        });
        PR1_Panel.add(PR1_InputArea_Sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 380, 70));

        PR1_Input_Label1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        PR1_Input_Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PR1_Input_Label1.setText("8 Programs");
        PR1_Panel.add(PR1_Input_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 240, 20));

        PR1_Input_Label2.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        PR1_Input_Label2.setText("2nd Input");
        PR1_Panel.add(PR1_Input_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, 40));

        PR1_Input_Label3.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        PR1_Input_Label3.setText("Input");
        PR1_Panel.add(PR1_Input_Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 40));
        PR1_Panel.add(PR1_Vert_Filler, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 10, 40));

        Content.add(PR1_Panel, "card3");

        PR2_Panel.setBackground(new java.awt.Color(255, 255, 204));
        PR2_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR2_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PR2_Clear_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR2_Clear_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR2_Clear_Btn.setText("Clear");
        PR2_Clear_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR2_Clear_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR2_Clear_BtnActionPerformed(evt);
            }
        });
        PR2_Panel.add(PR2_Clear_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 190, 60));

        PR2_Compute_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR2_Compute_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR2_Compute_Btn.setText("Compute");
        PR2_Compute_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR2_Compute_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR2_Compute_BtnActionPerformed(evt);
            }
        });
        PR2_Panel.add(PR2_Compute_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 190, 60));
        PR2_Panel.add(PR2_Buffer_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 110, 30));

        PR2_OutputArea.setBackground(new java.awt.Color(153, 255, 153));
        PR2_OutputArea.setColumns(20);
        PR2_OutputArea.setRows(5);
        PR2_OutputArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR2_OutputArea.setEditable(false);
        PR2_OutputArea.setFocusable(false);
        PR2_OutputArea.setCursor(null);
        PR2_Output_Scroll.setViewportView(PR2_OutputArea);

        PR2_Panel.add(PR2_Output_Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 590, 100));

        PR2_Next_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR2_Next_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR2_Next_Btn.setText("Next Program");
        PR2_Next_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR2_Next_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR2_Next_BtnActionPerformed(evt);
            }
        });
        PR2_Panel.add(PR2_Next_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 120, 40));

        PR2_Back_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR2_Back_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR2_Back_Btn.setText("Previous Program");
        PR2_Back_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR2_Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR2_Back_BtnActionPerformed(evt);
            }
        });
        PR2_Panel.add(PR2_Back_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 110, 40));

        PR2_Label_Input.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        PR2_Label_Input.setText("Simple Interest Calculator");
        PR2_Panel.add(PR2_Label_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        PR2_Return_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR2_Return_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR2_Return_Btn.setText("Return to Menu");
        PR2_Return_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR2_Return_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR2_Return_BtnActionPerformed(evt);
            }
        });
        PR2_Panel.add(PR2_Return_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 110, 40));

        PR2_InitVal_Input.setBackground(new java.awt.Color(153, 255, 153));
        PR2_InitVal_Input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR2_InitVal_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR2_InitVal_InputActionPerformed(evt);
            }
        });
        PR2_Panel.add(PR2_InitVal_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 370, 60));

        PR2_IntRate_Input.setBackground(new java.awt.Color(153, 255, 153));
        PR2_IntRate_Input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR2_IntRate_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR2_IntRate_InputActionPerformed(evt);
            }
        });
        PR2_Panel.add(PR2_IntRate_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 170, 60));

        PR2_TimeYr_Input.setBackground(new java.awt.Color(153, 255, 153));
        PR2_TimeYr_Input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR2_TimeYr_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR2_TimeYr_InputActionPerformed(evt);
            }
        });
        PR2_Panel.add(PR2_TimeYr_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 170, 60));

        Label_PrincipalAmount.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        Label_PrincipalAmount.setText("Principal Amount");
        PR2_Panel.add(Label_PrincipalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        PR2_Label_Years.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        PR2_Label_Years.setText("Amount of Years");
        PR2_Panel.add(PR2_Label_Years, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        PR2_Rate.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        PR2_Rate.setText("Interest Rate(1-100)");
        PR2_Panel.add(PR2_Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        PR2_Label_Output.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        PR2_Label_Output.setText("Output");
        PR2_Panel.add(PR2_Label_Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        PR2_Label_Input1.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        PR2_Label_Input1.setText("Input");
        PR2_Panel.add(PR2_Label_Input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));
        PR2_Panel.add(PR2_Vert_Filler, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 10, 40));

        Content.add(PR2_Panel, "card4");

        PR3_Panel.setBackground(new java.awt.Color(255, 255, 204));
        PR3_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR3_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PR3_Clear_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR3_Clear_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR3_Clear_Btn.setText("Clear");
        PR3_Clear_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR3_Clear_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_Clear_BtnActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_Clear_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 190, 60));
        PR3_Panel.add(PR3_rightFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 110, 10));

        PR3_About.setBackground(new java.awt.Color(153, 153, 255));
        PR3_About.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR3_About.setText("About Group");
        PR3_About.setBorder(new javax.swing.border.MatteBorder(null));
        PR3_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_AboutActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_About, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 120, 40));

        PR3_Back.setBackground(new java.awt.Color(153, 153, 255));
        PR3_Back.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR3_Back.setText("Previous Program");
        PR3_Back.setBorder(new javax.swing.border.MatteBorder(null));
        PR3_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_BackActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 110, 40));

        PR3_Compute_Btn.setBackground(new java.awt.Color(153, 153, 255));
        PR3_Compute_Btn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR3_Compute_Btn.setText("Compute");
        PR3_Compute_Btn.setBorder(new javax.swing.border.MatteBorder(null));
        PR3_Compute_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_Compute_BtnActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_Compute_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 190, 60));

        PR3_Return.setBackground(new java.awt.Color(153, 153, 255));
        PR3_Return.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        PR3_Return.setText("Return to Menu");
        PR3_Return.setBorder(new javax.swing.border.MatteBorder(null));
        PR3_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_ReturnActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 110, 40));

        PR3_PrincipalAmount_Label.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        PR3_PrincipalAmount_Label.setText("Compounded in one \"Time/Year\" ");
        PR3_Panel.add(PR3_PrincipalAmount_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, 10));

        PR3_FutVal_Output.setBackground(new java.awt.Color(153, 255, 153));
        PR3_FutVal_Output.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR3_FutVal_Output.setEditable(false);
        PR3_FutVal_Output.setFocusable(false);
        PR3_FutVal_Output.setCursor(null);
        PR3_FutVal_Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_FutVal_OutputActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_FutVal_Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 370, 50));

        PR3_IntEarn_Label.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        PR3_IntEarn_Label.setText("Interest Earned");
        PR3_Panel.add(PR3_IntEarn_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 10));

        PR3_Input_InterestRate.setBackground(new java.awt.Color(153, 255, 153));
        PR3_Input_InterestRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR3_Input_InterestRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_Input_InterestRateActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_Input_InterestRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 170, 40));

        PR3_Input_TimeYear.setBackground(new java.awt.Color(153, 255, 153));
        PR3_Input_TimeYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR3_Input_TimeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_Input_TimeYearActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_Input_TimeYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 170, 40));

        PR3_Years_Input.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        PR3_Years_Input.setText("Amount of Years");
        PR3_Panel.add(PR3_Years_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, 10));

        PR3_Input_Label.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        PR3_Input_Label.setText("Input");
        PR3_Panel.add(PR3_Input_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        PR3_Input_InitialValue.setBackground(new java.awt.Color(153, 255, 153));
        PR3_Input_InitialValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR3_Input_InitialValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_Input_InitialValueActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_Input_InitialValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 370, 40));

        PR3_Annual_Toggle.setBackground(new java.awt.Color(204, 204, 204));
        PR3_Annual_Toggle.setFont(new java.awt.Font("Garamond", 0, 12)); // NOI18N
        PR3_Annual_Toggle.setText("Annually=1");
        PR3_Annual_Toggle.setMaximumSize(new java.awt.Dimension(140, 30));
        PR3_Annual_Toggle.setMinimumSize(new java.awt.Dimension(140, 30));
        PR3_Annual_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_Annual_ToggleActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_Annual_Toggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 120, 30));

        Semi_Annuall_Toggle.setBackground(new java.awt.Color(204, 204, 204));
        Semi_Annuall_Toggle.setFont(new java.awt.Font("Garamond", 0, 12)); // NOI18N
        Semi_Annuall_Toggle.setText("Semi-Anually = 2");
        Semi_Annuall_Toggle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Semi_Annuall_Toggle.setMaximumSize(new java.awt.Dimension(140, 30));
        Semi_Annuall_Toggle.setMinimumSize(new java.awt.Dimension(140, 30));
        Semi_Annuall_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Semi_Annuall_ToggleActionPerformed(evt);
            }
        });
        PR3_Panel.add(Semi_Annuall_Toggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 120, 30));

        Monthly_Toggle.setBackground(new java.awt.Color(204, 204, 204));
        Monthly_Toggle.setFont(new java.awt.Font("Garamond", 0, 12)); // NOI18N
        Monthly_Toggle.setText("Monthly=12");
        Monthly_Toggle.setMaximumSize(new java.awt.Dimension(140, 30));
        Monthly_Toggle.setMinimumSize(new java.awt.Dimension(140, 30));
        Monthly_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Monthly_ToggleActionPerformed(evt);
            }
        });
        PR3_Panel.add(Monthly_Toggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, 30));

        Weekly_Toggle.setBackground(new java.awt.Color(204, 204, 204));
        Weekly_Toggle.setFont(new java.awt.Font("Garamond", 0, 12)); // NOI18N
        Weekly_Toggle.setText("Weekly = 52");
        Weekly_Toggle.setMaximumSize(new java.awt.Dimension(140, 30));
        Weekly_Toggle.setMinimumSize(new java.awt.Dimension(140, 30));
        Weekly_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Weekly_ToggleActionPerformed(evt);
            }
        });
        PR3_Panel.add(Weekly_Toggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 100, 30));

        Quarterly_Toggle.setBackground(new java.awt.Color(204, 204, 204));
        Quarterly_Toggle.setFont(new java.awt.Font("Garamond", 0, 12)); // NOI18N
        Quarterly_Toggle.setText("Quarterly = 4");
        Quarterly_Toggle.setMaximumSize(new java.awt.Dimension(140, 30));
        Quarterly_Toggle.setMinimumSize(new java.awt.Dimension(140, 30));
        Quarterly_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quarterly_ToggleActionPerformed(evt);
            }
        });
        PR3_Panel.add(Quarterly_Toggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 100, 30));

        Daily_Toggle.setBackground(new java.awt.Color(204, 204, 204));
        Daily_Toggle.setFont(new java.awt.Font("Garamond", 0, 12)); // NOI18N
        Daily_Toggle.setText("Daily = 365");
        Daily_Toggle.setMaximumSize(new java.awt.Dimension(140, 30));
        Daily_Toggle.setMinimumSize(new java.awt.Dimension(140, 30));
        Daily_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Daily_ToggleActionPerformed(evt);
            }
        });
        PR3_Panel.add(Daily_Toggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 90, 30));

        PR3_IntEarn_Output.setBackground(new java.awt.Color(153, 255, 153));
        PR3_IntEarn_Output.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PR3_IntEarn_Output.setEditable(false);
        PR3_IntEarn_Output.setFocusable(false);
        PR3_IntEarn_Output.setCursor(null);
        PR3_IntEarn_Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PR3_IntEarn_OutputActionPerformed(evt);
            }
        });
        PR3_Panel.add(PR3_IntEarn_Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 370, 50));

        PR3_Output_Label.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        PR3_Output_Label.setText("Output");
        PR3_Panel.add(PR3_Output_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        PR3_IntRate_Label.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        PR3_IntRate_Label.setText("Interest Rate(1-100)");
        PR3_Panel.add(PR3_IntRate_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 10));

        PR3_FutVal_Label.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        PR3_FutVal_Label.setText("Future Value");
        PR3_Panel.add(PR3_FutVal_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        Label_PrincipalAmount2.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        Label_PrincipalAmount2.setText("Principal Amount");
        PR3_Panel.add(Label_PrincipalAmount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, 10));

        Label_PrincipalAmount3.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        Label_PrincipalAmount3.setText("Select the Number of Times");
        PR3_Panel.add(Label_PrincipalAmount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, 10));

        PR3_Label.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        PR3_Label.setText("Compound Interest Calculator");
        PR3_Panel.add(PR3_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));
        PR3_Panel.add(PR3_Vert_Filler, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 10, 50));

        Content.add(PR3_Panel, "card5");

        AbtGrp_Panel.setBackground(new java.awt.Color(255, 255, 204));
        AbtGrp_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        AbtGrp_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AbtGrp_Return.setBackground(new java.awt.Color(153, 153, 255));
        AbtGrp_Return.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        AbtGrp_Return.setText("Return to Menu");
        AbtGrp_Return.setBorder(new javax.swing.border.MatteBorder(null));
        AbtGrp_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbtGrp_ReturnActionPerformed(evt);
            }
        });
        AbtGrp_Panel.add(AbtGrp_Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 110, 50));

        NameGrp.setBackground(new java.awt.Color(204, 255, 204));
        NameGrp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Members.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        Members.setText("Members");

        Bonifacio.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        Bonifacio.setText("Bonifacio, James Craven");

        jLabel38.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        jLabel38.setText("Chen, Kenneth");

        jLabel39.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        jLabel39.setText("Fernandez, Vhenz Angelo A.");

        jLabel40.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        jLabel40.setText("Litaban, Winfred Mikhail");

        jLabel41.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        jLabel41.setText("Paculan, Mikhaela Abbygail");

        jLabel12.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        jLabel12.setText("Sulit, Ruzzel Mae");

        javax.swing.GroupLayout NameGrpLayout = new javax.swing.GroupLayout(NameGrp);
        NameGrp.setLayout(NameGrpLayout);
        NameGrpLayout.setHorizontalGroup(
            NameGrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NameGrpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NameGrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NameGrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NameGrpLayout.createSequentialGroup()
                            .addComponent(Members)
                            .addGap(147, 147, 147))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NameGrpLayout.createSequentialGroup()
                            .addGroup(NameGrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Bonifacio, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(62, 62, 62)))
                    .addGroup(NameGrpLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        NameGrpLayout.setVerticalGroup(
            NameGrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NameGrpLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Members)
                .addGap(27, 27, 27)
                .addComponent(Bonifacio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        AbtGrp_Panel.add(NameGrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 500, 340));
        AbtGrp_Panel.add(PR3_Vert_Filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 10, 50));
        AbtGrp_Panel.add(AbtGrp_rightFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 110, 30));

        AbtGrp_Label.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        AbtGrp_Label.setText("ICC 0103-2 | BSCS 1-2 SY 2024-25");
        AbtGrp_Panel.add(AbtGrp_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        Content.add(AbtGrp_Panel, "card6");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P1_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR1_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P1_BtnActionPerformed

    private void P4_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P4_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR3_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P4_BtnActionPerformed

    private void AbtGroup_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbtGroup_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(AbtGrp_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_AbtGroup_BtnActionPerformed

    private void MainComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MainComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_MainComponentHidden

    private void PR2_Compute_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR2_Compute_BtnActionPerformed
        // TODO add your handling code here:
        int P, R, T;
        double I;

        try {
            P = Integer.parseInt(PR2_InitVal_Input.getText());
            R = Integer.parseInt(PR2_IntRate_Input.getText());
            T = Integer.parseInt(PR2_TimeYr_Input.getText());

            if (R > 100) {
                PR2_OutputArea.setText("Please follow the set Range given for Interest Rate.");
                return;
            } else if (R < 1) {
                PR2_OutputArea.setText("Please follow the set Range given for Interest Rate.");
                return;
            }
            I = (P*R*T) / 100;
            PR2_OutputArea.setText(I + "");
        } catch (NumberFormatException ex) {
            PR2_OutputArea.setText("One or more Inputs are Invalid or Missing!");
        }
    }//GEN-LAST:event_PR2_Compute_BtnActionPerformed

    private void PR2_Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR2_Back_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR1_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_PR2_Back_BtnActionPerformed

    private void PR1_InputArea_MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_InputArea_MainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR1_InputArea_MainActionPerformed

    private void PR1_Return_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_Return_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(Main);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_PR1_Return_BtnActionPerformed

    private void PR2_Return_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR2_Return_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(Main);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_PR2_Return_BtnActionPerformed

    private void AbtGrp_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbtGrp_ReturnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(Main);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_AbtGrp_ReturnActionPerformed

    private void PR3_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_BackActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR2_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_PR3_BackActionPerformed

    private void PR3_Compute_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_Compute_BtnActionPerformed
        // TODO add your handling code here:
        int R, T;
        double P;

        try {
            P = Double.parseDouble(PR3_Input_InitialValue.getText());
            R = Integer.parseInt(PR3_Input_InterestRate.getText());
            T = Integer.parseInt(PR3_Input_TimeYear.getText());

            if (R > 100) {
                PR3_FutVal_Output.setText("Please follow the set Range given for Interest Rate.");
                PR3_IntEarn_Output.setText("");
                return;
            } else if (R < 1) {
                PR3_FutVal_Output.setText("Please follow the set Range given for Interest Rate.");
                PR3_IntEarn_Output.setText("");
                return;
            }
            if (N == 0) {
                PR3_FutVal_Output.setText("Please select a Number of Times Conpounded.");
                PR3_IntEarn_Output.setText("");
                return;
            }
            
            double A = P * Math.pow(1 + (R / 100.0) / N, N * T);
            double I = A - P;
                    
            PR3_FutVal_Output.setText(String.format("%.2f", A));
            PR3_IntEarn_Output.setText(String.format("%.2f", I));
        } catch (NumberFormatException ex) {
            PR3_FutVal_Output.setText("One or more Inputs are Invalid or Missing!");
            PR3_IntEarn_Output.setText("");
        }
    }//GEN-LAST:event_PR3_Compute_BtnActionPerformed

    private void PR3_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_ReturnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(Main);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_PR3_ReturnActionPerformed

    private void P2_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR1_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P2_BtnActionPerformed

    private void P3_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P3_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR2_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P3_BtnActionPerformed

    private void P5_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P5_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR1_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P5_BtnActionPerformed

    private void P6_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P6_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR1_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P6_BtnActionPerformed

    private void P7_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P7_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR1_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P7_BtnActionPerformed

    private void P8_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P8_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR1_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P8_BtnActionPerformed

    private void P9_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P9_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR1_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P9_BtnActionPerformed

    private void P10_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P10_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR1_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_P10_BtnActionPerformed

    private void PR1_Next_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_Next_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR2_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_PR1_Next_BtnActionPerformed

    private void PR2_Next_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR2_Next_BtnActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(PR3_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_PR2_Next_BtnActionPerformed

    private void PR3_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_AboutActionPerformed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(AbtGrp_Panel);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_PR3_AboutActionPerformed

    private void PR2_InitVal_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR2_InitVal_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR2_InitVal_InputActionPerformed

    private void PR2_IntRate_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR2_IntRate_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR2_IntRate_InputActionPerformed

    private void PR2_TimeYr_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR2_TimeYr_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR2_TimeYr_InputActionPerformed

    private void PR2_Clear_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR2_Clear_BtnActionPerformed
        // TODO add your handling code here:
        PR2_Clear_Btn.addActionListener(n -> {
            PR2_InitVal_Input.setText("");
            PR2_IntRate_Input.setText("");
            PR2_TimeYr_Input.setText("");
            PR2_OutputArea.setText("");
        });
    }//GEN-LAST:event_PR2_Clear_BtnActionPerformed

    private void PR3_FutVal_OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_FutVal_OutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR3_FutVal_OutputActionPerformed

    private void PR3_Input_InterestRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_Input_InterestRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR3_Input_InterestRateActionPerformed

    private void PR3_Input_TimeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_Input_TimeYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR3_Input_TimeYearActionPerformed

    private void PR3_Input_InitialValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_Input_InitialValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR3_Input_InitialValueActionPerformed

    private void PR3_Annual_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_Annual_ToggleActionPerformed
        N = 1;
        highlightSelectedButton(PR3_Annual_Toggle);
    }//GEN-LAST:event_PR3_Annual_ToggleActionPerformed

    private void Semi_Annuall_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Semi_Annuall_ToggleActionPerformed
        N = 2;
        highlightSelectedButton(Semi_Annuall_Toggle);
    }//GEN-LAST:event_Semi_Annuall_ToggleActionPerformed

    private void Monthly_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Monthly_ToggleActionPerformed
        N = 12;
        highlightSelectedButton(Monthly_Toggle);
    }//GEN-LAST:event_Monthly_ToggleActionPerformed

    private void Weekly_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Weekly_ToggleActionPerformed
        N = 52;
        highlightSelectedButton(Weekly_Toggle);
    }//GEN-LAST:event_Weekly_ToggleActionPerformed

    private void Quarterly_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quarterly_ToggleActionPerformed
        N = 4;
        highlightSelectedButton(Quarterly_Toggle);
    }//GEN-LAST:event_Quarterly_ToggleActionPerformed

    private void Daily_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Daily_ToggleActionPerformed
        N = 365;
        highlightSelectedButton(Daily_Toggle);
    }//GEN-LAST:event_Daily_ToggleActionPerformed

    private void PR3_IntEarn_OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_IntEarn_OutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR3_IntEarn_OutputActionPerformed

    private void PR3_Clear_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR3_Clear_BtnActionPerformed
        // TODO add your handling code here:
        PR3_Clear_Btn.addActionListener(n -> {
            PR3_Input_InitialValue.setText("");
            PR3_Input_InterestRate.setText("");
            PR3_Input_TimeYear.setText("");
            PR3_FutVal_Output.setText("");
            PR3_IntEarn_Output.setText("");
        });
    }//GEN-LAST:event_PR3_Clear_BtnActionPerformed

    private void PR1_SqrRtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_SqrRtActionPerformed
        // TODO add your handling code here:
         try {
            String str = PR1_InputArea_Main.getText();
            double num = Double.parseDouble(str);

            if (num >= 0) {
                double squareRoot = Math.sqrt(num);
                if (squareRoot == Math.floor(squareRoot)) {
                    PR1_OutputArea.setText(PR1_OutputArea.getText() + "The square root of " + (int)num + " is " + (int)squareRoot + "\n");
                } else {
                    PR1_OutputArea.setText(PR1_OutputArea.getText() + (int)num + " does not have a perfect integer square root.\n");
                }
            } else {
                PR1_OutputArea.setText(PR1_OutputArea.getText() + "Cannot calculate the square root of a negative number.\n");
            }
        } catch (NumberFormatException e) {
            PR1_OutputArea.setText(PR1_OutputArea.getText() + "Invalid input. Please enter a valid number.\n");
        }
    }//GEN-LAST:event_PR1_SqrRtActionPerformed

    private void PR1_CubeRtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_CubeRtActionPerformed
        // TODO add your handling code here:
        try {
            String str = PR1_InputArea_Main.getText();
            double num = Double.parseDouble(str);

            double cubeRoot = Math.cbrt(num);
            if (cubeRoot == Math.floor(cubeRoot)) {
                PR1_OutputArea.setText(PR1_OutputArea.getText() + "The cube root of " + (int)num + " is " + (int)cubeRoot + "\n");
            } else {
                PR1_OutputArea.setText(PR1_OutputArea.getText() + (int)num + " does not have a perfect integer cube root.\n");
            }
        } catch (NumberFormatException e) {
            PR1_OutputArea.setText(PR1_OutputArea.getText() + "Invalid input. Please enter a valid number.\n");
        }
    }//GEN-LAST:event_PR1_CubeRtActionPerformed

    private void PR1_Clear_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_Clear_BtnActionPerformed
        // TODO add your handling code here:\
        PR1_InputArea_Main.setText("");
        PR1_OutputArea.setText("");
    }//GEN-LAST:event_PR1_Clear_BtnActionPerformed

    private void PR1_RandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_RandActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        int randomNumber = random.nextInt(1000) + 1; 
        PR1_OutputArea.setText("Random Number: " + randomNumber);
    }//GEN-LAST:event_PR1_RandActionPerformed

    private void PR1_BinToOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_BinToOctActionPerformed
        // TODO add your handling code here:
        String binaryInput = PR1_InputArea_Main.getText().trim();
    
    if (binaryInput.matches("[01]+")) {
        int decimal = Integer.parseInt(binaryInput, 2); 
        String octal = Integer.toOctalString(decimal); 
        PR1_OutputArea.setText(" " + octal);
    } else {
        PR1_OutputArea.setText("Invalid Binary Input. Please enter only 0s and 1s.");
    }
    
    }//GEN-LAST:event_PR1_BinToOctActionPerformed

    private void PR1_CelToFarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_CelToFarActionPerformed
        // TODO add your handling code here:
        String input = PR1_InputArea_Main.getText();
    
        if (input.matches("-?\\d+(\\.\\d+)?")) { 
            double celsius = Double.parseDouble(input);
            double fahrenheit = (celsius * 1.8) + 32;
        
            PR1_OutputArea.setText(input+ "°C is " + String.format("%.2f", fahrenheit) + "°F");
        } else {
            PR1_OutputArea.setText("Invalid input! Please enter a number.");
        }
    }//GEN-LAST:event_PR1_CelToFarActionPerformed

    private void PR1_FarToCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_FarToCelActionPerformed
        // TODO add your handling code here:
        String input = PR1_InputArea_Main.getText();
    
        if (input.matches("-?\\d+(\\.\\d+)?")) { // Check if input is a valid number
            double fahrenheit = Double.parseDouble(input);
            double celsius = (fahrenheit - 32) / 1.8;
            
            PR1_OutputArea.setText(input+ "°F is " + String.format("%.2f", celsius)+ "°C");
        } else {
            PR1_OutputArea.setText("Invalid input! Please enter a number.");
        }
    }//GEN-LAST:event_PR1_FarToCelActionPerformed

    private void PR1_FactorialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_FactorialsActionPerformed
        // TODO add your handling code here:
    try {
        int num = Integer.parseInt(PR1_InputArea_Main.getText());
        if (num < 0) {
            PR1_OutputArea.setText("Please input positive integers only!");
            return;
        }
        long factorial = 1;
        for (int i = 1; i <= num; i++) {
            factorial *= i;
        }
        PR1_OutputArea.setText("Factorial of " + num + " is: " + factorial);

    } catch (NumberFormatException e) {
        PR1_OutputArea.setText("Please enter a valid integer.");
    }
    }//GEN-LAST:event_PR1_FactorialsActionPerformed

    private void PR1_LeastCmonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_LeastCmonMultActionPerformed
        // TODO add your handling code here:
        try {
        int num1 = Integer.parseInt(PR1_InputArea_Sub.getText());
        int num2 = Integer.parseInt(PR1_InputArea_Main.getText());
        if (num1 <= 0 || num2 <= 0) {
            PR1_OutputArea.setText("Please enter positive integers only.");
            return;
        }

        int max = Math.max(num1, num2);
        int lcm = max;
        while (true) {
            if (lcm % num1 == 0 && lcm % num2 == 0) {
                break;
            }
            lcm++;
        }

        PR1_OutputArea.setText("LCM of " + num1 + " and " + num2 + " is: " + lcm);
    } catch (NumberFormatException e) {
        PR1_OutputArea.setText("Please enter valid integers in both fields.");
    }
    }//GEN-LAST:event_PR1_LeastCmonMultActionPerformed

    private void PR1_InputArea_SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PR1_InputArea_SubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PR1_InputArea_SubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainConsole_Draft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainConsole_Draft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainConsole_Draft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainConsole_Draft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainConsole_Draft().setVisible(true);
            }
        });
    }

    private void highlightSelectedButton(JToggleButton selected) {
    JToggleButton[] toggleButtons = {
        PR3_Annual_Toggle, Semi_Annuall_Toggle, Quarterly_Toggle,
        Monthly_Toggle, Weekly_Toggle, Daily_Toggle
    };

    for (JToggleButton button : toggleButtons) {
        if (button == selected) {
            button.setContentAreaFilled(true);
            button.setBackground(new java.awt.Color(0, 204, 51));
            button.setForeground(Color.WHITE);
        } else {
            button.setBackground(new java.awt.Color(204, 204, 204));
            button.setForeground(null);
            button.setOpaque(false);
            button.setContentAreaFilled(true); // Keep button shape
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbtGroup_Btn;
    private javax.swing.JLabel AbtGrp_Label;
    private javax.swing.JPanel AbtGrp_Panel;
    private javax.swing.JButton AbtGrp_Return;
    private javax.swing.Box.Filler AbtGrp_rightFill;
    private javax.swing.JLabel Bonifacio;
    private javax.swing.JPanel Content;
    public javax.swing.JToggleButton Daily_Toggle;
    private javax.swing.JLabel Label_PrincipalAmount;
    private javax.swing.JLabel Label_PrincipalAmount2;
    private javax.swing.JLabel Label_PrincipalAmount3;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel MainTitle2;
    private javax.swing.JLabel Main_Label;
    private javax.swing.JLabel Members;
    public javax.swing.JToggleButton Monthly_Toggle;
    private javax.swing.JPanel NameGrp;
    private javax.swing.JButton P10_Btn;
    private javax.swing.JButton P1_Btn;
    private javax.swing.JButton P2_Btn;
    private javax.swing.JButton P3_Btn;
    private javax.swing.JButton P4_Btn;
    private javax.swing.JButton P5_Btn;
    private javax.swing.JButton P6_Btn;
    private javax.swing.JButton P7_Btn;
    private javax.swing.JButton P8_Btn;
    private javax.swing.JButton P9_Btn;
    private javax.swing.JButton PR1_BinToOct;
    private javax.swing.JButton PR1_CelToFar;
    private javax.swing.JButton PR1_Clear_Btn;
    private javax.swing.JButton PR1_CubeRt;
    private javax.swing.JButton PR1_Factorials;
    private javax.swing.JButton PR1_FarToCel;
    private javax.swing.JTextField PR1_InputArea_Main;
    private javax.swing.JTextField PR1_InputArea_Sub;
    private javax.swing.JLabel PR1_Input_Label1;
    private javax.swing.JLabel PR1_Input_Label2;
    private javax.swing.JLabel PR1_Input_Label3;
    private javax.swing.JButton PR1_LeastCmonMult;
    private javax.swing.JButton PR1_Next_Btn;
    private javax.swing.JTextArea PR1_OutputArea;
    private javax.swing.JLabel PR1_Output_Label;
    private javax.swing.JScrollPane PR1_Output_Scroll;
    private javax.swing.JPanel PR1_Panel;
    private javax.swing.JButton PR1_Rand;
    private javax.swing.JButton PR1_Return_Btn;
    private javax.swing.JButton PR1_SqrRt;
    private javax.swing.Box.Filler PR1_Vert_Filler;
    private javax.swing.JButton PR2_Back_Btn;
    private javax.swing.Box.Filler PR2_Buffer_1;
    private javax.swing.JButton PR2_Clear_Btn;
    private javax.swing.JButton PR2_Compute_Btn;
    private javax.swing.JTextField PR2_InitVal_Input;
    private javax.swing.JTextField PR2_IntRate_Input;
    private javax.swing.JLabel PR2_Label_Input;
    private javax.swing.JLabel PR2_Label_Input1;
    private javax.swing.JLabel PR2_Label_Output;
    private javax.swing.JLabel PR2_Label_Years;
    private javax.swing.JButton PR2_Next_Btn;
    private javax.swing.JTextArea PR2_OutputArea;
    private javax.swing.JScrollPane PR2_Output_Scroll;
    private javax.swing.JPanel PR2_Panel;
    private javax.swing.JLabel PR2_Rate;
    private javax.swing.JButton PR2_Return_Btn;
    private javax.swing.JTextField PR2_TimeYr_Input;
    private javax.swing.Box.Filler PR2_Vert_Filler;
    private javax.swing.JButton PR3_About;
    public javax.swing.JToggleButton PR3_Annual_Toggle;
    private javax.swing.JButton PR3_Back;
    private javax.swing.JButton PR3_Clear_Btn;
    private javax.swing.JButton PR3_Compute_Btn;
    private javax.swing.JLabel PR3_FutVal_Label;
    private javax.swing.JTextField PR3_FutVal_Output;
    private javax.swing.JTextField PR3_Input_InitialValue;
    private javax.swing.JTextField PR3_Input_InterestRate;
    private javax.swing.JLabel PR3_Input_Label;
    private javax.swing.JTextField PR3_Input_TimeYear;
    private javax.swing.JLabel PR3_IntEarn_Label;
    private javax.swing.JTextField PR3_IntEarn_Output;
    private javax.swing.JLabel PR3_IntRate_Label;
    private javax.swing.JLabel PR3_Label;
    private javax.swing.JLabel PR3_Output_Label;
    private javax.swing.JPanel PR3_Panel;
    private javax.swing.JLabel PR3_PrincipalAmount_Label;
    private javax.swing.JButton PR3_Return;
    private javax.swing.Box.Filler PR3_Vert_Filler;
    private javax.swing.Box.Filler PR3_Vert_Filler1;
    private javax.swing.JLabel PR3_Years_Input;
    private javax.swing.Box.Filler PR3_rightFill;
    private javax.swing.JToggleButton Quarterly_Toggle;
    public javax.swing.JToggleButton Semi_Annuall_Toggle;
    public javax.swing.JToggleButton Weekly_Toggle;
    private javax.swing.Box.Filler filler35;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.Box.Filler main_spacefill_left;
    private javax.swing.Box.Filler main_spacefill_right;
    // End of variables declaration//GEN-END:variables
}
